# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # 使用 npm 作为包管理器 See documentation for possible values
    directory: "/frontend"   # 指定 frontend 目录 Location of package manifests
    schedule:
      interval: "weekly"     # 每周检查一次更新
    commit-message:
      prefix: "deps"         # PR 提交信息前缀
